/**
 * Stable, machine-readable error codes.
 *
 * These are part of the public API contract: clients switch on them, so a
 * code must never be reworded or repurposed once shipped. The human-facing
 * `message` beside it may change freely.
 *
 * Grouped by domain, prefixed by domain, SCREAMING_SNAKE_CASE.
 */
export enum ErrorCode {
  // ── Generic ────────────────────────────────────────────────
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION',

  // ── Authentication / authorization ─────────────────────────
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_WRONG_REALM = 'AUTH_WRONG_REALM',
  AUTH_REFRESH_INVALID = 'AUTH_REFRESH_INVALID',
  AUTH_REFRESH_REUSED = 'AUTH_REFRESH_REUSED',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_PASSWORD_CHANGE_REQUIRED = 'AUTH_PASSWORD_CHANGE_REQUIRED',
  AUTH_FORBIDDEN_ROLE = 'AUTH_FORBIDDEN_ROLE',

  // ── Scope (row-level access) ───────────────────────────────
  /**
   * Reserved for genuine capability denials. Cross-scope access to another
   * chain's data resolves to NOT_FOUND instead, so the API never confirms
   * that a record the actor may not see exists.
   */
  SCOPE_FORBIDDEN = 'SCOPE_FORBIDDEN',

  // ── Staff / hierarchy ──────────────────────────────────────
  STAFF_NOT_FOUND = 'STAFF_NOT_FOUND',
  STAFF_EMAIL_TAKEN = 'STAFF_EMAIL_TAKEN',
  STAFF_USERNAME_TAKEN = 'STAFF_USERNAME_TAKEN',
  STAFF_INVALID_HIERARCHY = 'STAFF_INVALID_HIERARCHY',
  STAFF_CANNOT_MANAGE_PEER = 'STAFF_CANNOT_MANAGE_PEER',
  STAFF_HAS_DEPENDENTS = 'STAFF_HAS_DEPENDENTS',

  // ── Customers ──────────────────────────────────────────────
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_EMAIL_TAKEN = 'CUSTOMER_EMAIL_TAKEN',
  CUSTOMER_USERNAME_TAKEN = 'CUSTOMER_USERNAME_TAKEN',
  CUSTOMER_SELF_UPDATE_FORBIDDEN = 'CUSTOMER_SELF_UPDATE_FORBIDDEN',
  CUSTOMER_INVALID_OWNER = 'CUSTOMER_INVALID_OWNER',

  // ── Transactions ───────────────────────────────────────────
  TX_NOT_FOUND = 'TX_NOT_FOUND',
  TX_AMOUNT_INVALID = 'TX_AMOUNT_INVALID',
  TX_CORRECTION_EXCEEDS_PARENT = 'TX_CORRECTION_EXCEEDS_PARENT',
  TX_CORRECTION_ON_CORRECTION = 'TX_CORRECTION_ON_CORRECTION',
  TX_ALREADY_REVERSED = 'TX_ALREADY_REVERSED',
  TX_FUTURE_DATED = 'TX_FUTURE_DATED',

  // ── Games ──────────────────────────────────────────────────
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  GAME_CODE_TAKEN = 'GAME_CODE_TAKEN',
  GAME_INACTIVE = 'GAME_INACTIVE',

  // ── VIP ────────────────────────────────────────────────────
  VIP_CRITERIA_NOT_FOUND = 'VIP_CRITERIA_NOT_FOUND',
  VIP_CRITERIA_INACTIVE = 'VIP_CRITERIA_INACTIVE',
  VIP_INVALID_PERIOD = 'VIP_INVALID_PERIOD',
  VIP_PERIOD_OVERLAP = 'VIP_PERIOD_OVERLAP',

  // ── Spin events ────────────────────────────────────────────
  SPIN_EVENT_NOT_FOUND = 'SPIN_EVENT_NOT_FOUND',
  SPIN_PRESELECTED_REQUIRES_WINNERS = 'SPIN_PRESELECTED_REQUIRES_WINNERS',
  SPIN_WINNER_NOT_VIP = 'SPIN_WINNER_NOT_VIP',
  SPIN_DUPLICATE_WINNER = 'SPIN_DUPLICATE_WINNER',
  SPIN_EVENT_NOT_OPEN = 'SPIN_EVENT_NOT_OPEN',

  // ── Referrals / bonuses ────────────────────────────────────
  REFERRAL_PROGRAM_NOT_FOUND = 'REFERRAL_PROGRAM_NOT_FOUND',
  REFERRAL_PROGRAM_EXPIRED = 'REFERRAL_PROGRAM_EXPIRED',
  REFERRAL_CODE_NOT_FOUND = 'REFERRAL_CODE_NOT_FOUND',
  REFERRAL_CODE_ALREADY_ASSIGNED = 'REFERRAL_CODE_ALREADY_ASSIGNED',
  REFERRAL_CODE_EXHAUSTED = 'REFERRAL_CODE_EXHAUSTED',
  REFERRAL_SELF_REFERRAL = 'REFERRAL_SELF_REFERRAL',

  // ── Messaging ──────────────────────────────────────────────
  CONVERSATION_NOT_FOUND = 'CONVERSATION_NOT_FOUND',
  MESSAGE_EMPTY = 'MESSAGE_EMPTY',
  CONVERSATION_CLOSED = 'CONVERSATION_CLOSED',
  STAFF_CANNOT_MESSAGE = 'STAFF_CANNOT_MESSAGE',

  // ── Email ──────────────────────────────────────────────────
  EMAIL_CAMPAIGN_NOT_FOUND = 'EMAIL_CAMPAIGN_NOT_FOUND',
  EMAIL_NO_RECIPIENTS = 'EMAIL_NO_RECIPIENTS',
  EMAIL_CAMPAIGN_ALREADY_SENT = 'EMAIL_CAMPAIGN_ALREADY_SENT',
  EMAIL_CAMPAIGN_NOT_CANCELLABLE = 'EMAIL_CAMPAIGN_NOT_CANCELLABLE',
  EMAIL_TRANSPORT_FAILED = 'EMAIL_TRANSPORT_FAILED',

  // ── Exports ────────────────────────────────────────────────
  EXPORT_DEFINITION_NOT_FOUND = 'EXPORT_DEFINITION_NOT_FOUND',
  EXPORT_JOB_NOT_FOUND = 'EXPORT_JOB_NOT_FOUND',
  EXPORT_JOB_NOT_READY = 'EXPORT_JOB_NOT_READY',
  EXPORT_JOB_EXPIRED = 'EXPORT_JOB_EXPIRED',
  EXPORT_TOO_LARGE = 'EXPORT_TOO_LARGE',
}
