/**
 * The API contract.
 *
 * These are **derived from the backend's OpenAPI document**, not written by
 * hand. `lib/api-schema.d.ts` is generated by `npm run types:api`, which
 * regenerates `backend/openapi.json` and converts it.
 *
 * This file exists so pages import `Customer` rather than
 * `components['schemas']['CustomerResponseDto']`, and so the envelope
 * generics below have somewhere to live. Adding a hand-written interface
 * for something the API returns defeats the point: an earlier hand-typed
 * version of this file type-checked cleanly while getting the login
 * payload, the dashboard shape and two list summaries wrong, and every one
 * of those surfaced as a broken page rather than a compile error.
 *
 * Money is `string` throughout because the API serialises `numeric(18,2)`
 * that way. See lib/money.ts.
 */

import type { components } from './api-schema';

type Schemas = components['schemas'];

/* ── Envelope ─────────────────────────────────────────────────────────── */

export type PaginationMeta = Schemas['PaginationMetaDto'];
export type ValidationDetail = Schemas['ValidationErrorDetailDto'];

/** Every successful response carries this envelope. */
export interface ApiEnvelope<TData, TSummary = undefined> {
  success: true;
  statusCode: number;
  message: string;
  data: TData;
  meta?: PaginationMeta;
  summary?: TSummary;
  timestamp: string;
  path: string;
  correlationId: string;
}

/** Failures replace `data` with `error`. */
export interface ApiErrorEnvelope {
  success: false;
  statusCode: number;
  message: string;
  error: {
    code: string;
    message: string;
    details: ValidationDetail[] | Record<string, unknown> | null;
  };
  timestamp: string;
  path: string;
  correlationId: string;
}

/** A page of rows plus the totals that describe the whole filtered set. */
export interface Paginated<TRow, TSummary = undefined> {
  data: TRow[];
  meta: PaginationMeta;
  summary?: TSummary;
}

/* ── Identity ─────────────────────────────────────────────────────────── */

export type Staff = Schemas['StaffResponseDto'];
export type StaffProfile = Schemas['StaffProfileDto'];
export type TeamLoginResponse = Schemas['TeamLoginResponseDto'];
export type StaffRole = Staff['role'];

/* ── Customers ────────────────────────────────────────────────────────── */

export type Customer = Schemas['CustomerResponseDto'];
export type CustomerSummary = Schemas['CustomerListSummaryDto'];
export type CustomerStatus = Customer['status'];

export type ImportRow = Schemas['ImportCustomerRowDto'];
export type ImportRowIssue = Schemas['ImportRowIssueDto'];
export type ImportPreview = Schemas['ImportPreviewResponseDto'];
export type CommitImportResult = Schemas['CommitImportResponseDto'];

/* ── Transactions ─────────────────────────────────────────────────────── */

export type Transaction = Schemas['TransactionResponseDto'];
export type TransactionSummary = Schemas['TransactionSummaryDto'];
export type TransactionType = Transaction['type'];

/* ── Dashboard ────────────────────────────────────────────────────────── */

export type DashboardMetrics = Schemas['DashboardResponseDto'];
export type GameTotal = Schemas['TopGameDto'];
export type TeamRollupRow = Schemas['TeamRollupRowDto'];
export type TrendPoint = Schemas['TrendPointDto'];
export type TrendResponse = Schemas['TrendResponseDto'];
export type TrendGranularity = TrendResponse['granularity'];

/* ── Staff management, games, VIPs, spins ─────────────────────────────── */

export type Game = Schemas['GameResponseDto'];
export type Vip = Schemas['VipResponseDto'];
export type VipCriteria = Schemas['VipCriteriaResponseDto'];
export type SpinEvent = Schemas['SpinEventResponseDto'];
export type SpinWinner = Schemas['SpinWinnerListItemDto'];
export type SpinWinnerSummary = Schemas['SpinWinnerSummaryDto'];

/* ── Messaging ────────────────────────────────────────────────────────── */

export type Conversation = Schemas['ConversationResponseDto'];
export type ConversationSummary = Schemas['ConversationSummaryDto'];
export type Message = Schemas['MessageResponseDto'];
export type MessageAttachment = Schemas['MessageAttachmentDto'];

/* ── Audit ────────────────────────────────────────────────────────────── */

export type AuditLog = Schemas['AuditLogDto'];
export type AuditLogSummary = Schemas['AuditLogSummaryDto'];
